import random

Evening = [
    [
        True,
        True,
        False,
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        False,
        False,
        False,
        True,
        False,
        False,
        False,
        False,
        False,
        False,
    ],
    [
        False,
        True,
        False,
        True,
        True,
        False,
        False,
        True,
        False,
        False,
        True,
        True,
        False,
        True,
        False,
        False,
        False,
        True,
        True,
        False,
    ],
    [
        False,
        True,
        True,
        True,
        False,
        True,
        False,
        True,
        True,
        True,
        True,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
        True,
    ],
    [
        False,
        False,
        False,
        False,
        True,
        True,
        False,
        False,
        False,
        True,
        True,
        False,
        False,
        True,
        False,
        True,
        True,
        False,
        False,
        False,
    ],
    [
        False,
        True,
        True,
        False,
        False,
        True,
        True,
        False,
        True,
        False,
        True,
        True,
        False,
        False,
        False,
        True,
        True,
        True,
        False,
        True,
    ],
    [
        True,
        True,
        False,
        True,
        True,
        True,
        False,
        True,
        True,
        True,
        True,
        False,
        True,
        False,
        False,
        True,
        True,
        False,
        True,
        False,
    ],
    [
        True,
        True,
        False,
        False,
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        False,
        False,
        False,
        False,
        True,
        False,
        False,
    ],
    [
        False,
        False,
        True,
        True,
        False,
        True,
        True,
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        False,
        False,
        False,
        False,
        True,
        False,
    ],
    [
        False,
        True,
        False,
        False,
        True,
        True,
        True,
        True,
        False,
        True,
        False,
        True,
        True,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
    ],
    [
        True,
        False,
        True,
        False,
        False,
        False,
        True,
        True,
        True,
        False,
        False,
        True,
        True,
        False,
        False,
        True,
        True,
        True,
        False,
        True,
    ],
]


num_of_booked_seats = 0

for row in Evening:
    for seat in row:
        if seat == True:
            num_of_booked_seats += 1

print(num_of_booked_seats, "has already booked.")


requested_seats = int(input("Enter num of seat : "))

if requested_seats <= 0 or requested_seats > 4:
    print("Invalid Input")

num_of_unbooked_seats = 200 - num_of_booked_seats

if requested_seats > num_of_unbooked_seats:
    if num_of_unbooked_seats == 0:
        print("House is full.")
    else:
        print("Only", num_of_unbooked_seats, "left.")
else:
    for row_num in range(10):
        for seat_num in range(20):
            seat = Evening[row_num][seat_num]
            if seat == False and requested_seats != 0:
                Evening[row_num][seat_num] = True
                requested_seats -= 1
                num_of_booked_seats += 1
                num_of_unbooked_seats -= 1

                print("you got row", row_num + 1, "seat", seat_num + 1)
